on: [push]
name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Generate and publish release and documentation
    if: github.repository_owner == 'laudrup'
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install APT packages
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -yq install \
        doxygen \
        libboost-dev \
        libssh2-1-dev \
        python3-pip
    - name: Install PIP packages
      # TODO: Consider using requirements.txt to ensure specific versions are used
      run: |
        sudo pip3 install \
        sphinx \
        breathe \
        sphinx_bootstrap_theme \
        sphinx_jinja \
        sphinxcontrib_jquery
    - name: Configure build system
      run: cmake -DBUILD_DOCUMENTATION=ON -B build
    - name: Build documentation
      run: cmake --build build/ --target doc
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs/html
