on: [push]
name: unittest

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        compiler: [gcc, clang]

    runs-on: ${{ matrix.platform }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install APT packages
      if: matrix.platform == 'ubuntu-latest'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -yq install \
        libssh2-1-dev \
        libboost-all-dev
    - name: Set conditional environment variables
      if: matrix.compiler == 'clang'
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
    - name: Configure
      run: cmake -B build
    - name: Build
      run: cmake --build build/
    - name: Run tests
      working-directory: build
      run: ctest
      env:
        CTEST_OUTPUT_ON_FAILURE: True
